### ISSUE TITLE
Support for 1.20.2+ and 1.21

### ISSUE THREAD

**Issue by ArselMuginov** [vanutp/tgbridge#2]
Hello! Was looking for an easy integration with Telegram and this mod seems great! Unfortunately I can't use it because my server is on 1.20.4.

Does it require more actions than changing versions in configs? I don't have experience with modding Minecraft so I'm not sure. But I'm a developer so I could make a merge request to add new versions support if you like.

**Comment by vanutp** [comment]
Hi! It might not be as easy as changing version number, as Minecraft's internal API changes a lot event between minor releases.
I can add 1.20.2+ support for Fabric, but I would prefer to skip Forge for 1.20.2+ and build for 1.21 when it's released, because of the NeoForge migration and the fact that most mods use 1.20.1.

**Comment by vanutp** [comment]
I have added Fabric 1.20.2, 1.20.4 and 1.20.6 support in the latest release (0.4.1)

**Comment by ArselMuginov** [comment]
I use Fabric so that's great! Thank you!
